<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tab</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Tablature</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^([a-z])(\|)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.pitch.string.tablature</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.barline.guitar.tablature</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>neck.guitar.tablature</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#neck</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^   +[A-Za-z].*</string>
			<key>name</key>
			<string>comment.lyrics.text.tablature</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^   +[ |]+</string>
			<key>name</key>
			<string>support.barlines.tablature</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>neck</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.repeat.barline.guitar.tablature</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.barline.guitar.tablature</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\:\d+)?(\|)</string>
					<key>name</key>
					<string>barline.guitar.tablature</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.note.guitar.tablature</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.transition.note.guitar.tablature</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.note.guitar.tablature</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>support.string.guitar.tablature</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((\d+)([hps]))?(\d+)([-|])</string>
					<key>name</key>
					<string>note.guitar.tablature</string>
				</dict>
				<dict>
					<key>match</key>
					<string>-</string>
					<key>name</key>
					<string>support.string.guitar.tablature</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.instruction.string.guitar.tablature</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\|(.*?)</string>
					<key>name</key>
					<string>instruction.guitar.tablature</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.tablature</string>
	<key>uuid</key>
	<string>FA4321C2-92BB-4630-BB2F-D8894D61D5EE</string>
</dict>
</plist>
